backend/models/user.js

The skills/interests/mentorship portion of the user database will come directly from the State that Peter had set up in Dashboard.js

Updating user model

---

server/chat-server/chat.js
server/server.js
src/App.js
src/components/common/DividingHeader.js
src/components/dashboard/Chat/ChatController.js
src/components/dashboard/Profile.js
src/components/dashboard/Profile/Career.js
src/components/dashboard/Profile/Certifications.js
src/components/dashboard/Profile/Collaboration.js
src/components/dashboard/Profile/Mentorship.js
src/components/dashboard/Profile/PersonalInfo.js
src/components/dashboard/Profile/SkillsAndInterests.js
src/components/dashboard/Profile/Social.js
src/styles/components/_Dashboard.scss
src/styles/components/_ProfileStyles.scss

just like the commit says, nothing a whole lot more this time. Major refactor though. Way better!

refactor profile page, small serverside changes

---

.gitignore
server/chat-server/chat.js
src/actions/chat.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/chat.js

Implements message editing and like features in chat with real-time updates to connected clients. Should correctly manage user edit and like capabilities based on message authorship.
[**Yay demo**](http://recordit.co/mihqkMYe8z)

Implemented edit and like features for chat

---

server/chat-server/chat.js
server/server.js
src/actions/chat.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/chat.js
src/styles/components/_Dashboard.scss

delete messages... some cool stuff...

Updates to chat features

---

server/helper_functions/mockData.js
server/server.js

Updated mock users code

---

src/components/common/DividingHeader.js
src/components/common/UserLabel.js
src/components/dashboard/Community.js
src/components/dashboard/Community/UserCard.js
src/components/dashboard/Profile.js
src/components/dashboard/Profile/SkillsAndInterests.js
src/styles/App.scss
src/styles/components/_CommunityStyles.scss

- added card reveal showing first 3 interests and skills on hover
- random refactors
http://recordit.co/8AI0MlG9x3

added reveal to card component

---

package.json
public/index.html
src/actions/chat.js
src/components/AppContainer.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/components/dashboard/Chat/ChatModal.js
src/reducers/privateChat.js
src/rootReducer.js
src/styles/components/_Dashboard.scss

[**React is King, v1 of Private Chat in < 5 hours**](http://recordit.co/YmDabx6UW5)
None of this involves the server yet, that's next.
Also updates Chat Emojis to match the Emoji Picker emojis.

Version 1 of Private Chat

---

server/chat/chat.js
server/models/private-chat.js
server/routes/private-chat.js
server/server.js
src/actions/chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/privateChat.js

This gets private chat onto the server and fetches private chat history for a user when they access the chat route in the app. Still need to implement `likes` feature everywhere and all real-time updates for private chat.

Initial work on establishing private chat on server

---

server/chat/chat.js
server/models/chat.js
server/routes/chat.js
server/routes/community.js
server/routes/private-chat.js
server/routes/user.js
server/server.js
src/actions/chat.js
src/actions/flashMessages.js
src/components/AppContainer.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/chat.js
src/reducers/privateChat.js
src/styles/components/_Dashboard.scss

**Community chat history is now stored in database, all chat actions are written consistently now and guarded with error checking and flash messages, private chat is (tentatively) fully implemented.**

Large refactor to chat

---

src/components/dashboard/Mentorship.js
src/styles/components/_Mentorship.scss

Small improvements to mentorship in case @no-stack-dub-sack gets back to this tomorrow morning before me. Mainly wiring up private chat creation to individual user cards and also (I think) preserving search results when toggling filters on and off.
Looks like PR also cleared out a lot of spaces...?

Minor improvements

---

server/chat/chat.js
server/routes/user.js
server/server.js
src/actions/onlineStatus.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/onlineStatus.js
src/rootReducer.js
src/styles/App.scss
src/styles/components/_Chat.scss

Implements mentor icons and online status in chat... Redis is back!

Added online-status and mentorship icon in chat

---

server/chat/chat.js
server/routes/chat.js
server/routes/private-chat.js
src/actions/chat.js
src/components/dashboard/Chat/Chat.js
src/components/dashboard/Chat/ChatController.js
src/reducers/chat.js
src/reducers/privateChat.js

**Implements:**
- Chat should scroll to bottom when component mounts.
- Support for `edited` status of messages (needs testing with multiple users).
- Tentative support for sending private messages *only* to target recipient *only if* they are currently online (needs testing with multiple users).

Edited status, scroll to bottom, privacy

---

client/src/components/dashboard/Chat/ChatController.js
client/src/reducers/privateChat.js

Attempt to fix private chat initialize bug

---

client/src/components/dashboard/Chat/Chat.js
client/src/components/dashboard/Chat/ChatController.js
client/src/components/dashboard/Chat/ChatModal.js
client/src/reducers/privateChat.js
client/src/styles/components/_Chat.scss
package.json
server/routes/passport.js

**Fixes various things in chat and also tries to setup `MongoStore` for session persistence on server.**
Frontend routing doesn't work in some cases...
- Trying to navigate to a user profile from within chat was not working and I couldn't figure out how to do it.
- Typing some URLs in directly does not work.

Improvements to chat

---

server/helpers/mockData.js

Added GitHub credentials for production mock data query

---

package.json

Trying to create better scripts in package.json to run and deploy the project.

Improved scripts in package.json

---

client/src/components/dashboard/Chat/Chat.js
client/src/components/dashboard/Chat/ChatController.js
client/src/styles/components/_Chat.scss

Minor improvements to styles in chat.

Minor improvements in chat

---

client/src/actions/chat.js
client/src/components/dashboard/Chat/ChatController.js
server/routes/chat.js

delete message was broken lolz

Fixes delete problem in global chat and some mobile styling

---

client/src/assets/data/countries.js
client/src/components/dashboard/Mentorship.js
client/src/components/dashboard/Profile/Mentorship.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/Public/FCCTables.js
client/src/components/dashboard/Profile/Public/LocationSteps.js
client/src/components/dashboard/Profile/Public/SkillsRow.js
client/src/components/dashboard/Profile/Public/SocialListItem.js
client/src/components/dashboard/Profile_Public.js

this renders even the sparsest of profiles with a nice looking UI.

conditional rendering for profile UI

---

client/src/App.js
client/src/components/AppContainer.js
client/src/components/Navbar.js
client/src/components/PublicLanding.js
client/src/styles/App.scss

**This PR implements:**
- 404 catch-all routes on public-facing pages and authentication-protected dashboard using React Router `Switch` component. I think these are working correctly.
- A public landing 'About' page with nice navbar styling for desktop and mobile which describes some basic information about the app.
@no-stack-dub-sack I'm going to merge this so I can redeploy all the various changes from the past 2 days. Also I think you added some better mobile styling for the login page, I want to see if this is working.
With this, other than other various ongoing efforts by @no-stack-dub-sack, I think this is getting very close to alpha release stage, aside from perhaps the landing page for the user dashboard.

Adds public landing page and 404 routes

---

client/src/components/Navbar.js
client/src/components/signup/LoginPage.js
client/src/styles/App.scss
client/src/styles/_animations.scss

Tries to fix nav and login page styling on mobile.

Fixes mobile styling for nav and login

---

client/src/App.js
client/src/assets/polyfills/string.js
client/src/components/Navbar.js
client/src/components/common/FormField.js
client/src/components/common/MessageBox.js
client/src/components/common/RepoList.js
client/src/components/dashboard/Community.js
client/src/components/dashboard/Community/SocialLinks.js
client/src/components/dashboard/Community/UserCard.js
client/src/components/dashboard/Profile/Career.js
client/src/components/dashboard/Profile/Mentorship.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/Public/ProfileHeader.js
client/src/components/dashboard/Profile/Public/SocialList.js
client/src/components/dashboard/Profile/Public/SocialListItem.js
client/src/components/dashboard/Profile/SkillsAndInterests.js
client/src/components/dashboard/Profile/common/RibbonHeader.js
client/src/components/dashboard/Profile/common/SaveModal.js
client/src/components/dashboard/Profile_Config.js
client/src/components/dashboard/Profile_Public.js
client/src/components/flash/FlashMessage.js
client/src/components/flash/FlashMessagesList.js
client/src/components/signup/LoginPage.js
client/src/styles/App.scss
client/src/styles/components/_SliderToggle.scss
client/src/styles/globalStyles.js

like I said, poor commit history here, not even sure of everything I did in this one! But most should be improvements to profile config mobile UI. Having some issues in some places but an improvement overall. Here goes an attempt at recounting tasks besides mobile UI improvements on profile page:
- fixed flash message on login page margin issue
- adds popups to profile page for info (email, social inputs)
- added validations for codepen field (no URLs allowed)
- adds polyfill for string methods
- changes user card clickability to username section instead of whole card, this is for improved mobile UI on community page
- replaces all font awesome FCC icons with Semantic native fcc icons - they do have an FCC one!

various mobile ui improvements & other misc.

---

client/src/App.js
client/src/components/HomePage.js
client/src/components/Navbar.js
client/src/components/PublicLanding.js
client/src/components/common/FormField.js
client/src/components/dashboard/Account.js
client/src/components/dashboard/Profile/Public/FCCTables.js
client/src/components/dashboard/Profile/common/RibbonHeader.js
client/src/components/dashboard/Profile_Public.js
client/src/components/flash/FlashMessagesList.js
client/src/components/signup/LoginPage.js
client/src/styles/App.scss

his screen cast & PR addresses the issue of margins on flash messages and page content changing at mobile UI sizes and when flash messages are rendered/cleared. Also one other small chore. 
http://recordit.co/UX14sOYo9z

flash message fixes, and other small chores

---

client/src/components/common/MessageBox.js
client/src/components/dashboard/Profile/Career.js
client/src/components/dashboard/Profile/Certifications.js
client/src/components/dashboard/Profile/Collaboration.js
client/src/components/dashboard/Profile/Mentorship.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/RepoList.js
client/src/components/dashboard/Profile/SkillsAndInterests.js
client/src/components/dashboard/Profile/Social.js
client/src/components/dashboard/Profile/common/RibbonHeader.js
client/src/components/dashboard/Profile_Config.js
client/src/styles/_helperClasses.scss
client/src/styles/components/_Profile.scss
client/src/styles/globalStyles.js

- fixes bug introduced to preferences page which was causing component to re-render and text entry to be choppy among other things (introduced a couple of PRs ago)
- makes some edits to styles on preferences page to make more consistent (hardly noticeable but cleaner overall)
- fixes dismissible message boxes for skills & interests and collaboration section (just remembered as I was pushing that I didn't fix the remaining ones - started that task yesterday on the train home and got distracted by the bug, will fix rest soon)

fix preferences page bug, make styles consistent

---

client/src/components/AppContainer.js
client/src/components/dashboard/Mentorship.js
client/src/components/dashboard/Mentorship/SearchResults.js
client/src/components/dashboard/Profile/Career.js
client/src/components/dashboard/Profile/Certifications.js
client/src/components/dashboard/Profile/Collaboration.js
client/src/components/dashboard/Profile/Mentorship.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/SkillsAndInterests.js
client/src/components/dashboard/Profile/Social.js
client/src/components/dashboard/Profile/common/RibbonHeader.js
client/src/components/dashboard/Profile_Config.js
client/src/reducers/search.js
client/src/styles/components/_Profile.scss

- improve mentorship UI
- fix mentorship location search (now searches country field as well)
- fix remaining message box conditional renderings 
Screen Cast of mentorship improvements: http://recordit.co/efQN2MvKF8

home stretch chores 

---

client/src/components/dashboard/Community/UserCard.js
client/src/components/dashboard/Mentorship.js
client/src/components/dashboard/Mentorship/SearchResults.js
client/src/components/dashboard/Profile_Config.js

- fixes mentorship search results to show regular bio when user is not mentor and placeholder when no bio is defined
- makes search filters fixed position when on desktop
- links mentorship search results to user profiles
- fixes `initiatePrivateChat` method in `Mentorship` to clear notifications if private chat already exists
- implements private chat links / icons in community `UserCard`s

link mentorship search results, private chat from community

---

client/package.json
client/src/App.test.js
client/src/actions/user.js
client/src/assets/polyfills/string.js
client/src/components/Navbar.js
client/src/components/dashboard/Community/CertLinks.js
client/src/components/dashboard/Community/UserCard.js
client/src/components/dashboard/Landing.js
client/src/components/dashboard/Mentorship.js
client/src/components/dashboard/Mentorship/SearchResults.js
server/routes/passport.js
server/routes/user.js

**This PR accomplishes several things:**
- Fixes authentication issue where navigating back after logout reached a semi-authenticated state by changing authentication check to a `post` request.
- Fixes `navbar` responsive styling. There was an issue when the navbar was the size of a tablet. Part of the issue is inconsistency between the width sizes Semantic UI responds to and the widths we have available via React screen-size. But this makes the  `navbar` respond better at all screen sizes.
- Updates `Mentorship/SearchResults.js` component to literally rely on the presence of search results rather than calculate this in the parent and pass additional props, i.e. `results.length` evaluates to `true/false` based on the presence/absence of results. I did this mainly because the 'No Results' …

Implements various improvements and fixes

---

client/src/components/common/UserLabel.js
client/src/components/dashboard/Profile/Career.js
client/src/components/dashboard/Profile/Certifications.js
client/src/components/dashboard/Profile/Collaboration.js
client/src/components/dashboard/Profile/Mentorship.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/SkillsAndInterests.js
client/src/components/dashboard/Profile/Social.js
client/src/components/dashboard/Profile_Config.js

This does improve the performance when typing in the text fields. It can still be slow if you type *very* fast, but I think this is faster than anyone can type normal sentences. I think the remaining performance problems are related to storing all the fields in one big state object which forces updates to copy this entire object instead of just updating one field, but I'm not 100% sure about this. Ideally, these would be separated like we talked about in the [GitHub issue](https://github.com/FCC-Alumni/alumni-network/issues/122), — however — if we feel like this is fast enough (I think it is, but may need to verify on mobile) we may want just go with this for now and re-evaluate later (post-production).
The class components all implement `shouldComponentUpdate` using lodash `isEqual` …

Refactors all profile children into class components

---

client/src/components/Navbar.js
client/src/components/dashboard/Community/UserCard.js
client/src/components/dashboard/Profile/PersonalInfo.js
client/src/components/dashboard/Profile/RepoList.js
client/src/components/dashboard/Profile/common/RibbonHeader.js
client/src/components/dashboard/Profile_Config.js

the `resolve merge conflicts` commit really includes some minor fixes in a few different components, but I had to overwrite to commit message when I rebased in the changes from your last PR due to some merge conflicts.
This also fixes the navbar issue and the reveal on mobile issue for the community component, we will have to deploy to see if it works though, it works locally but the dimensions changing on mobile may affect this. If so, we'll just revert that component and deal with it. This would mean there's no animation/transition, it just switches `display: none` on and off in a very contrived way to account for things like semantic class names. Let's give it a whirl and see what happens.

navbar refactor, fixes user card reveal on mobile

---

client/src/components/dashboard/Profile_Public.js

got this far, but struggled a bit in getting this data into redux the right way (without setting component state first and going from there). I think I had a poor approach though and just need to rethink it. Don't have time tonight though, we can chat more about this tomorrow.

convert scraping actions to single action

---

CONTRIBUTING.md
README.md

Adds readme and contributing boilerplate

---

client/src/components/dashboard/Chat/ChatController.js
client/src/components/dashboard/Landing.js
client/src/reducers/onlineStatus.js

@bonham000 also, seems like we can change the style of the popups, however the little pointing caret you cannot seem to change, so changing the background color is not really possible. But we can add box shadow, change font color, size, etc. 
Have anything in particular in mind? I tried a couple of things and nothing seemed quite right. Personally, I'm ok with the white on grey, both are officially FCC colors and don't think it looks all that bad, but if you can play around with it and come up with something good, go for it! Just pass in style prop to the `Popup` component.

added offline notification for private chat

---

client/src/actions/chat.js
server/chat/chat.js
server/routes/chat.js
server/routes/private-chat.js

This provides some notes on how chat works which I guess would be good to include because there is a pattern there. The idea is to leave some record for anyone who wants to work on this in the future.

Adds notes about chat

---

client/src/assets/dropdowns/countries.js
client/src/components/dashboard/Profile/Preferences/common/RepoList.js
client/src/styles/App.scss
package.json

UPDATES:
1. Added a button to add projects by click on it. Pressing `enter` still works as it did before.
1. Did some minor refactoring with the `RepoList` component RegEx and a few other things.
1. There was a warning in the console about having an empty 'flag' value on the countries object, so I removed it.
The relevant issue is #191

small refactoring, error fix, and UI changes for collaboration section

---

.circleci/config.yml
client/package-lock.json
client/package.json
package-lock.json

Needs @no-stack-dub-sack to set up CircleCI for this to work.
Depends on #222 
fixes #189 
Should configure repo so tests must pass to merge PR

add CircleCI

---

server/routes/community.js

redact private data from API
